# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VlGBQFM83_FupOg1Lq3DXufuIg4SEXn
"""

pip install google-play-scraper

from google_play_scraper import reviews, Sort
import csv

result, _ = reviews(
    'id.go.kemnaker.siapkerja',
    lang='id',
    country='id',
    sort=Sort.NEWEST,
    count=100,
    filter_score_with=None
)

filename = 'ulasan_google_play.csv'


with open(filename, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=['userName', 'score', 'at', 'content'])
    writer.writeheader()
    for review in result:

        writer.writerow({
            'userName': review['userName'],
            'score': review['score'],
            'at': review['at'],
            'content': review['content']
        })

print(f"Berhasil menyimpan {len(result)} ulasan ke '{filename}'")

import pandas as pd

df = pd.read_csv('ulasan_google_play.csv')
display(df.head())

from transformers import pipeline

# Re-initialize the sentiment pipeline to ensure it's available
sentiment_pipeline = pipeline("sentiment-analysis", model="w11wo/indonesian-roberta-base-sentiment-classifier")

# Perform sentiment analysis on the 'content' column
df['sentiment_result'] = df['content'].apply(lambda x: sentiment_pipeline(x)[0])
df['sentiment_label'] = df['sentiment_result'].apply(lambda x: x['label'])
df['sentiment_score'] = df['sentiment_result'].apply(lambda x: x['score'])

display(df[['content', 'sentiment_label', 'sentiment_score']].head())

import matplotlib.pyplot as plt
import seaborn as sns

# Count the occurrences of each sentiment label
sentiment_counts = df['sentiment_label'].value_counts().reset_index()
sentiment_counts.columns = ['Sentiment', 'Count']

# Create a bar plot for sentiment distribution
plt.figure(figsize=(8, 6))
sns.barplot(x='Sentiment', y='Count', data=sentiment_counts, hue='Sentiment', palette='viridis', legend=False)
plt.title('Distribution of Sentiment Labels')
plt.xlabel('Sentiment')
plt.ylabel('Number of Reviews')
plt.show()

# Create a pie chart for sentiment proportion
plt.figure(figsize=(8, 8))
plt.pie(sentiment_counts['Count'], labels=sentiment_counts['Sentiment'], autopct='%1.1f%%', startangle=140, colors=sns.color_palette('viridis'))
plt.title('Proportion of Sentiment Labels')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis", model="w11wo/indonesian-roberta-base-sentiment-classifier")

"""Melakukan analisis sentimen pada kolom `content`."""

df['sentiment_result'] = df['content'].apply(lambda x: sentiment_pipeline(x)[0])
df['sentiment_label'] = df['sentiment_result'].apply(lambda x: x['label'])
df['sentiment_score'] = df['sentiment_result'].apply(lambda x: x['score'])

display(df[['content', 'sentiment_label', 'sentiment_score']].head())

import pandas as pd

df = pd.read_csv('ulasan_google_play.csv')
display(df.head())

pip install transformers torch

from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis", model="w11wo/indonesian-roberta-base-sentiment-classifier")

"""Melakukan analisis sentimen pada kolom `content`."""

df['sentiment_result'] = df['content'].apply(lambda x: sentiment_pipeline(x)[0])
df['sentiment_label'] = df['sentiment_result'].apply(lambda x: x['label'])
df['sentiment_score'] = df['sentiment_result'].apply(lambda x: x['score'])

display(df[['content', 'sentiment_label', 'sentiment_score']].head())